# Generated by Django 5.1.6 on 2025-02-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_megazine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megazine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='megazine',
            name='megazine_body',
        ),
        migrations.AddField(
            model_name='megazine',
            name='magazine_body',
            field=models.TextField(default='No content available'),
        ),
        migrations.AlterField(
            model_name='megazine',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='megazine',
            name='short_desc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='megazine',
            name='status',
            field=models.CharField(choices=[('default', 'draft'), ('published', 'published')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='megazine',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='megazine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
