# Generated by Django 5.1.6 on 2025-02-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megazine',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
