# Generated by Django 5.1.6 on 2025-02-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_smalling'),
    ]

    operations = [
        migrations.CreateModel(
            name='MustRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='must_reads/images/')),
                ('link', models.URLField()),
            ],
        ),
    ]
