# Generated by Django 5.1.6 on 2025-02-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_mustread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmallIng',
        ),
    ]
