# Generated by Django 5.1.6 on 2025-02-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_delete_smalling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mustread',
            name='description',
        ),
    ]
