# Generated by Django 5.1.6 on 2025-02-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_cards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MustRead',
        ),
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name_plural': 'Cards'},
        ),
    ]
