# Generated by Django 5.1.6 on 2025-02-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_delete_mustread_alter_cards_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Crd',
        ),
    ]
