# Generated by Django 5.1.6 on 2025-02-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_rename_cards_crd'),
    ]

    operations = [
        migrations.AddField(
            model_name='crd',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
