# Generated by Django 5.1.6 on 2025-02-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_crd_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('world', 'World'), ('business', 'Business'), ('technology', 'Technology'), ('sports', 'Sports'), ('health', 'Health'), ('entertainment', 'Entertainment')], default='world', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='featured_posts/images/')),
                ('link', models.URLField()),
            ],
        ),
    ]
