# Generated by Django 5.1.6 on 2025-02-08 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_leftcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftcontent',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='newapp.category'),
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
