# Generated by Django 5.1.6 on 2025-02-08 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_leftcontent_category_alter_featuredpost_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftcontent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='newapp.category'),
        ),
    ]
