# Generated by Django 5.1.6 on 2025-02-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_alter_leftcontent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftcontent',
            name='category',
        ),
    ]
